name: new react workflow
on:
  push:
    branches:
      - main
    # paths-ignore:
    #   - ".github/workflows/*.yml"
  workflow_dispatch:
jobs:
  appbuild:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1

      - name: install dependencies
        run: npm install

      - name: lint
        run: npm run lint

      - name: test
        run: npm run test

      - name: build
        run: npm run build

      - name: saving artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist
            package.json

      - name: deploy
        run: echo "deploying application..."